use cargo_metadata::MetadataCommand;
use std::env;
use std::fs::File;
use std::io::Write;
use std::path::PathBuf;

fn main() {
    //  Re-run build.rs when Cargo.toml is modified
    println!("cargo:rerun-if-changed=Cargo.toml");

    // Retrieve the Cargo metadata for the current project
    let metadata = MetadataCommand::new()
        .exec()
        .expect("Failed to parse cargo metadata");

    let root_pkg = metadata
        .root_package()
        .expect("Root package not found in metadata");

    // Retrieve the prefix from [package.metadata.plugin.prefix] (use [package].name as the default value)
    let prefix = root_pkg
        .metadata
        .get("plugin")
        .and_then(|p| p.get("prefix"))
        .and_then(|v| v.as_str())
        .map(|s| s.to_string())
        .unwrap_or_else(|| format!("{}-plugin-", root_pkg.name));

    // Match entries in [dependencies] that match the prefix
    let mut plugins = Vec::new();
    for dep in &root_pkg.dependencies {
        if dep.name.starts_with(&prefix) {
            let crate_name = dep.name.replace('-', "_");
            plugins.push(crate_name);
        }
    }

    // Write to `generated_plugins.rs` in `OUT_DIR`
    let out_dir = PathBuf::from(env::var("OUT_DIR").unwrap());
    let dest_path = out_dir.join("generated_plugins.rs");
    let mut file = File::create(dest_path).unwrap();

    writeln!(file, "// Auto-generated by build.rs. Do not edit.").unwrap();
    for plugin in plugins {
        writeln!(file, "use {} as _;", plugin).unwrap();
    }
}
